# ----
# Site

title: 당근저장소
url: "https://redcarrot01.github.io/"
baseurl: "/"
# google_analytics_key: "UA-165000136-2"
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/siteicon.png
description: 
author: redcarrot01
email: redcarrot01@gmail.com
twitter: # twitter username without the @ symbol
type: website

# Conversion
markdown: kramdown
highlighter: rouge

# Math equation
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Build
encoding: utf-8
permalink: pretty

# image url settings
algorithm_img: /images/Algorithm
datastructure_img: /images/Datastructure
network_img: /images/Network
web_img: /images/Web
spring_img: /images/Web/Spring
tech_img: /images/Tech

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release


types:
  - minor
  - major

# Themplate https://github.com/CloudCannon/edition-jekyll-template
